exports.htmlMixinPlugin = require('./htmlMixin')
exports.cssMixinPlugin = require('./cssMixin')
exports.polyfillPlugin = require('./polyfill')
exports.jsPreProcessPlugin = require('./jsPreProcess')
exports.cssPreProcessPlugin = require('./cssPreProcess')
exports.htmlPreProcessPlugin = require('./htmlPreProcess')
exports.jsMixinPlugin = require('./jsMixin')
exports.setLibrary = require('./setLibrary')
